name: CI

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Copy .env.example files
        shell: bash
        run: find . type -name ".env.example" -exec sh -c 'cp "$1" "${1/.env.example/.env}"' _ {} \;

      - name: Typecheck
        run: pnpm typecheck
